server:
 port: 8002

spring:
 dubbo:
  application:
   name: dubbo_a
  protocol:
   name: dubbo
   port: 20882
  registry:
   protocol: zookeeper
   address: dev.cdh.ecarx.local:2181
  monitor:
   protocol: registry
   address: dev.cdh.ecarx.local:2181
  ##scan: com.kaka.jtest.provider.biz.service