server:
 port: 8001

spring:
 dubbo:
  application1:
   name: dubbo_a
  protocol:
   name: dubbo
   port: 20880
  registry:
   protocol: zookeeper
   address: 10.43.100.169:2181
  monitor:
   protocol: registry
   address: 10.43.100.169:2181
