server:
 port: 8002

spring:
 dubbo:
  application:
   name: jsk_provider
  protocol:
   name: dubbo
   port: 20882
  registry:
   protocol: zookeeper
   address: 127.0.0.1:2181
  monitor:
   protocol: registry
   address: 127.0.0.1:2181
  ##scan: com.kaka.jtest.provider.biz.service
dubbo:
 configcenter: zookeeper://10.43.104.122:2181