server:
 port: 8002

spring:
 dubbo:
  application:
   name: jsk_provider
  protocol:
   name: dubbo
   port: 20882
  registry:
   protocol: zookeeper
   address: dev.cdh.jsk.local:2181
  monitor:
   protocol: registry
   address: dev.cdh.jsk.local:2181
  ##scan: com.kaka.jtest.provider.biz.service

# config.center与健康检查有冲突
#dubbo:
# configcenter: zookeeper://dev.cdh.jsk.local:2181

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    dubboreferences:
     enabled: true
    dubboservices:
     enabled: true
    dubboshutdown:
     enabled: true