server:
  port: 8081

logging:
  level:
    root: INFO

job:
  zkConfig:
    zkConnectString: dev.cdh.jsk.local:2181
    rootPath: /tb-schedule/test-task
    zkSessionTimeout: 60000
    userName: jsk
    password: jsk
    isCheckParentPath: true