server:
 port: 8004

spring:
 dubbo:
  application:
   name: jsk_consumer
  protocol:
   name: dubbo
   port: 20884
  registry:
   protocol: zookeeper
   address: 127.0.0.1:2181
  monitor:
   protocol: registry
   address: 127.0.0.1:2181
#  scan: com.kaka.jtest.consumer.boot.controller