server:
 port: 8004

spring:
 dubbo:
  application:
   name: jsk_consumer
  protocol:
   name: dubbo
   port: 20884
  registry:
   protocol: zookeeper
   address: dev.cdh.jsk.local:2181
  monitor:
   protocol: registry
   address: dev.cdh.jsk.local:2181
#  scan: com.kaka.jtest.consumer.boot.controller

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    dubboreferences:
     enabled: true
    dubboservices:
     enabled: true
    dubboshutdown:
     enabled: true