server:
 port: 8002

spring:
 dubbo:
  application:
   name: dubbo_b
  protocol:
   name: dubbo
   port: 20881
  registry:
   protocol: zookeeper
   address: 10.43.100.169:2181
  monitor:
   protocol: registry
   address: 10.43.100.169:2181
  scan: com.kaka.jtest.consumer.call