server:
 port: 8004

spring:
 dubbo:
  application:
   name: dubbo_b
  protocol:
   name: dubbo
   port: 20884
  registry:
   protocol: zookeeper
   address: dev.cdh.ecarx.local:2181
  monitor:
   protocol: registry
   address: dev.cdh.ecarx.local:2181
  scan: com.kaka.jtest.consumer.boot.controller